stages:
  - build
  - test
  - deploy

buildtest-node:
  image: node:latest
  stage: build
  script:
    - apt-get update -qy
    - cd code
    - npm install

docker-test:
  image: docker:latest
  services:
    - docker:dind
  stage: test
  script:
    - cd code
    - docker login registry.gitlab.com -u {username} -p {access_token}
    - docker build -t registry.gitlab.com/wilsonltl/pso2-keeper-renew .
    - docker run -d -p 80:3000 registry.gitlab.com/wilsonltl/pso2-keeper-renew

docker-deploy:
  image: docker:latest
  services:
    - docker:dind
  stage: deploy
  script:
    - cd code
    - docker login registry.gitlab.com -u {username} -p {access_token}
    - docker build -t registry.gitlab.com/wilsonltl/pso2-keeper-renew .
    - docker push registry.gitlab.com/wilsonltl/pso2-keeper-renew
  only:
      - master




